### ISSUE TITLE
Re-Export ApiClientError from @mittwald/api-client-commons

### ISSUE THREAD

**Issue by martin-helmich** [mittwald/api-client-js#172]
From https://github.com/mittwald/contributor-support/issues/2:

> Ich würde gerne beim Error Handling überprüfen ob es ein allgemeiner Error ist oder ein Error den das SDK wirft. Das ist besonders mit TypeScript hilreich.
> 
> Beispiel:
> ```
> if (error instanceof ApiClientError) {
>     ...
> }
> ```
> 
> Der `ApiClientError` existiert und wird in der [Doku](https://www.npmjs.com/package/@mittwald/api-client) erwähnt, leider wird er nicht exportiert.

**Comment by martin-helmich** [comment]
@mfal Thoughts? We already re-export a few symbols (like `assertStatus`) from `@mittwald/api-client-commons`:

https://github.com/mittwald/api-client-js/blob/8052a83b1cb4e9518f76cf296627ec14f46b3208/packages/mittwald/src/index.ts#L1-L5

**Comment by mfal** [comment]
Re-exporting just `*` should do better.
